
(define-abbrev-table 'global-abbrev-table '(
    ("9b" "birbiriyle" nil 1)
    ("9ba" "baglantili" nil 1)
    ("9ca" "Calculus" nil 1)
    ("9de" "degiskenler" nil 1)
    ("9di" "diferansiyel" nil 1)
    ("9e" "e^{}" move-back-one-char 0)
    ("9f" "formul" nil 1)
    ("9fo" "fonksiyonu" nil 1)
    ("9fr" "\\frac{}{}" move-back-three-chars 0)
    ("9ge" "geometrik" nil 1)
    ("9h" "hesapla" nil 1)
    ("9inv" "^{-1}" nil 1)
    ("9g" "goruldugu" nil 1)
    ("9kk" "kullanacagiz" nil 1)
    ("9ki" "kismi turevler" nil 1)
    ("9l" "_{}^{}" move-back-four-chars 0)
    ("9lim" "\\lim_{h \\to 0}" move-back-one-char 0)
    ("9L" "\\mathcal{L}\\bigg( \\bigg)" move-back-seven-chars 0)
    ("9u" "ustteki" nil 1)
    ("9U" "Ustteki" nil 1)
    ("9o" "o zaman" nil 1)
    ("9O" "O zaman" nil 1)
    ("9p" "\\frac{\\partial }{\\partial x}" nil 1)
;;    ("9s" "\\sqrt{}" move-back-one-char 1)
    ("9ya" "yaklasiksallama" nil 1)
    ))
